### ISSUE TITLE
Programmatically selectShow popups instead of an user click

### ISSUE THREAD

**Issue by ghost** [jorix/OL-FeaturePopups#13]
I use a filter strategy and I'd like to programmatically select the feature (selectShow popups) instead of an user click. Is this possible ?

**Comment by jorix** [comment]
Hi @robertico01 

Yes, there are two ways to do it.

NOTE: Use the new branch: https://github.com/jorix/OL-FeaturePopups/tree/goal-v110
1. Use internal SelectFeature control of FeaturePopups as: `fpControl.controls.select.select(feature);` and `.unselectAll()`
2. Use FeaturePopups selection functions by id: `addSelectionByIds`, `setSelectionByIds`, `removeSelectionByIds` as in examples _grid-jqGrid-features.html_ and _grid-SlickGrid-features.html_ (In these examples is synchronized the selection of the grid with selection on the map)
3. You can display a single popup without selecting a feature, see `showSingleFeatureById` also in the grid examples.

This part of the FeaturePopups code ( _2._ & _3._) has not been mentioned on issues of other users, I guess it has not been used. So ask if problems arise ;-)

If using the cluster strategy, the first option _1._ only allows sectioning layer features, so clusters. The second _2._ & _3._ only selected individual features and acts through the cluster transparently as if you do not use the cluster strategy.

**Warning**: On **goal-v110** branch the first parameter of xxxSelectionByIds and showSingleFeatureById functions becomes the _layer_ instead of its _id_, and are in a separate code file _FeaturePopupsExtend.js_.

**Comment by jorix** [comment]
NOTE: It is important to understand that the `id` of the features is the `fid` when this exists. 

NOTE 2: To use the functions `xxxSelectionByIds` should be used the mode SAFE_SELECTION (is used by default)

**Comment by ghost** [comment]
Thank you very much. I'll give it a try.
I need some time to study the examples you mentioned. I'm not a programmer but an amateur. 
So far I've got it all working ;-) Thanks for your help

**Comment by jorix** [comment]
I close this issue, open it freely if you need further clarification.
