### ISSUE TITLE
Fixed possition of Popup

### ISSUE THREAD

**Issue by emog** [jorix/OL-FeaturePopups#27]
I have a fixed size FramedCloud Popup that I want to position relative to the point calling it, always above the point and with its right side 50px to the right of the point. How can i do this with FeaturePopups. Because now it changes popup possition according to the angle of feature is hovered.

**Comment by jorix** [comment]
This is an issue concerning OpenLayers, and only affects this control in a little detail.

---

To control the position of popups you could do a trick:

``` js
    var myPopupClass = OpenLayers.Class(OpenLayers.Popup.FramedCloud, {
        calculateRelativePosition:function() { return 'tr'; },
        relativePosition: 'tr'
    });
```

and then use `myPopupClass` instead of `OpenLayers.Popup.FramedCloud`.

---

But `FeaturePopups` also uses the same trick for `listItem` popups, so if you have this code:

``` js
    var fpControl = new OpenLayers.Control.FeaturePopups({
        popupOptions:{
            list:{popupClass:myPopupClass},
            single:{popupClass:myPopupClass},
            listItem:{popupClass:myPopupClass}
        }, ...
   ...
   });
```

`listItem` popups are show as `'br'`, this is logical, since this way you can see the list and the item  (not the list under de item)
